### ISSUE TITLE
where did llgo go?

### ISSUE THREAD

**Issue by glycerine** [go-llvm/llgo#225]
I'm looking for llgo on llvm.org but I can't find any trace.

Could somebody put links on the README to point better to where llgo discussion and where llgo code went?

Llgo seemed so alive. Now it seems dead and gone without a trace.

**Comment by sbinet** [comment]
over there http://llvm.org/viewvc/llvm-project/llgo/ ?

**Comment by glycerine** [comment]
thanks @sbinet . Looks like it is there, just hidden away off in its own private Idaho.

It's kind of amazing how much more visible github makes projects, progress, and collaboration.

Oh well, glad it's not gone. Maybe somebody could setup a mirror to github?

**Comment by axw** [comment]
@glycerine there are unofficial GitHub mirrors for other LLVM projects at https://github.com/llvm-mirror, but llgo hasn't been set up. I'll see if I can find out how to get llgo on there.

It'd probably help if there were mentions of llgo on llvm.org, too.

**Comment by mewmew** [comment]
> It's kind of amazing how much more visible github makes projects, progress, and collaboration.

I just wanted to second this. I know this may not be the right forum for a discussion, but the issue title struck home. It made perfect sense to me that go-llvm should live with llvm.org as it can keep in sync with the release cycles of the rest of the project. The `llgo` Go compiler however feels much less visible now. I know development is still happening over at llvm.org, and that reviews are made available through Phabricator.

Andrew, would you like to share with us your impression of how the project (llgo specifically, not go-llvm) has been affected by the move to llvm.org. Is it a net win? What have been the ups and the downs? Are more seasoned LLVM developers now working on the code base? How is the feedback from the community, in form of reported issues, comments on code reviews, (pull requests), etc?

Would really love to hear it in your own words.

**Comment by axw** [comment]
@mewmew Honestly, I think it's much of a muchness so far. Probably the biggest difference is that the build system is better integrated with LLVM now. There have been a couple of small fixes since by people other than myself and Peter. There are as many regular contributors before and after.

I hope things will get a little better, quality wise, once there's a buildbot slave in place. I've written the code, I just need to set up the slave. Once that's available, LLVM and Clang developers will be informed when their (LLVM/Clang) changes break the llgo build.

Once nightly builds are set up, I'll start looking into Debian/Ubuntu packaging; I'm hoping to piggy-back onto the existing LLVM packages. That will give (some) people a way to play with llgo without having to go through the process of building LLVM, Clang and llgo from source.

I didn't get any response regarding the mirror, so I might end up making go-llvm/llgo a read-only mirror.

**Comment by mewmew** [comment]
Thanks for the update Andrew! I really appreciate it.

**Comment by glycerine** [comment]
> so I might end up making go-llvm/llgo a read-only mirror

@axw That would be excellent; yes, please do.

**Comment by tony** [comment]
https://github.com/llvm-mirror/llgo

**Comment by axw** [comment]
Thanks, @tony!

**Comment by glycerine** [comment]
Given https://github.com/llvm-mirror/llgo, closing this.
